/*
 * This file is generated by jOOQ.
 */
package ru.rtmis.melfor.camel.jooq.schema.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Mapping implements Serializable {

    private static final long serialVersionUID = 742584363;

    private final Integer systemId;
    private final String  id;
    private final String  first;
    private final String  second;

    public Mapping(Mapping value) {
        this.systemId = value.systemId;
        this.id = value.id;
        this.first = value.first;
        this.second = value.second;
    }

    public Mapping(
        Integer systemId,
        String  id,
        String  first,
        String  second
    ) {
        this.systemId = systemId;
        this.id = id;
        this.first = first;
        this.second = second;
    }

    public Integer getSystemId() {
        return this.systemId;
    }

    public String getId() {
        return this.id;
    }

    public String getFirst() {
        return this.first;
    }

    public String getSecond() {
        return this.second;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Mapping (");

        sb.append(systemId);
        sb.append(", ").append(id);
        sb.append(", ").append(first);
        sb.append(", ").append(second);

        sb.append(")");
        return sb.toString();
    }
}
