/*
 * This file is generated by jOOQ.
 */
package ru.rtmis.melfor.camel.jooq.schema;


import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;

import ru.rtmis.melfor.camel.jooq.schema.tables.Mapping;
import ru.rtmis.melfor.camel.jooq.schema.tables.records.MappingRecord;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<MappingRecord> MAPPING_SYSTEM_ID_KEY = UniqueKeys0.MAPPING_SYSTEM_ID_KEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<MappingRecord> MAPPING_SYSTEM_ID_KEY = Internal.createUniqueKey(Mapping.MAPPING, "mapping_system_id_key", new TableField[] { Mapping.MAPPING.SYSTEM_ID }, true);
    }
}
