/*
 * This file is generated by jOOQ.
 */
package ru.rtmis.melfor.camel.jooq.schema;


import ru.rtmis.melfor.camel.jooq.schema.tables.Mapping;


/**
 * Convenience access to all tables in public
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.mapping</code>.
     */
    public static final Mapping MAPPING = Mapping.MAPPING;
}
